# Generated by Django 2.2.3 on 2019-07-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='state',
            field=models.CharField(max_length=40, verbose_name='Estado'),
        ),
    ]
