# Generated by Django 2.2.3 on 2019-07-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_auto_20190727_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='comp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento'),
        ),
    ]
